// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1juWcF0YV9ZYVr4Vds0vsdEoptMF854Y',
    appId: '1:57039413702:web:b9f1409544db36100dd2c7',
    messagingSenderId: '57039413702',
    projectId: 'notekeeping-project-flutter',
    authDomain: 'notekeeping-project-flutter.firebaseapp.com',
    storageBucket: 'notekeeping-project-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz7Fo3t7Qxz4BhFygo-LBY0h2aaJZeIG0',
    appId: '1:57039413702:android:c1f4b256eca5b2b20dd2c7',
    messagingSenderId: '57039413702',
    projectId: 'notekeeping-project-flutter',
    storageBucket: 'notekeeping-project-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_ow0V1yDEC-MjTAJ5q7OoRpLOEsylHI',
    appId: '1:57039413702:ios:738d7af034634d110dd2c7',
    messagingSenderId: '57039413702',
    projectId: 'notekeeping-project-flutter',
    storageBucket: 'notekeeping-project-flutter.appspot.com',
    iosClientId: '57039413702-4md5rcbb7fdubk1j3fnu5ah7v3mr8aat.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
